### ISSUE TITLE
Error pops up when resizing the window

### ISSUE THREAD

**Issue by cscherrNT** [MeanderingProgrammer/dashboard.nvim#4]
```lua
Error executing lua callback: ...ocal/share/nvim/lazy/dashboard.nvim/lua/dashboard/ui.lua:39: Invalid buffer id: 1
stack traceback:
	[C]: in function '__newindex'
	...ocal/share/nvim/lazy/dashboard.nvim/lua/dashboard/ui.lua:39: in function 'load'
	...al/share/nvim/lazy/dashboard.nvim/lua/dashboard/init.lua:46: in function <...al/share/nvim/lazy/dashboard.nvim/lua/dashboard/init.lua:45>
```

Apparently, the bufnr passed to  `load` in `ui.lua` is wrong?

Context: This happens when I'm just editing, the dashboard i not opened

**Comment by MeanderingProgrammer** [comment]
Can you update the plugin and see if the error persists? 

There was a somewhat recent update that should prevent this: https://github.com/MeanderingProgrammer/dashboard.nvim/commit/4a0fe3ad97ae29859ee02fad61dc203c9d3e5f76. Based on the line numbers in your error message you're on a version before this update.

If you still get the error can you describe what you do to trigger it, i.e.:

- Open neovim dashboard
- Click key to open project
- Open any file in project
- Resize neovim

Something to that effect.

**Comment by cscherrNT** [comment]
I can't reproduce it anymore on 4a0fe3a. I thought I did update already and still had the issue on 4a0fe3a, but apparently not?

Thanks for fixing it and making this plugin available :) Happy editing.
